# Generated by Django 3.2.9 on 2021-12-23 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_commentevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='descimage2',
            field=models.ImageField(default='', upload_to='image'),
        ),
        migrations.AddField(
            model_name='events',
            name='descimage3',
            field=models.ImageField(default='', upload_to='image'),
        ),
        migrations.AlterField(
            model_name='events',
            name='descimage',
            field=models.ImageField(default='', upload_to='image'),
        ),
    ]
